"""initial schema

Revision ID: 38415c5003e6
Revises: 
Create Date: 2026-07-31 05:41:03.292170

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '38415c5003e6'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analytics_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('event_type', sa.String(length=32), nullable=False),
    sa.Column('user_id_anon', sa.String(length=64), nullable=False),
    sa.Column('payload_json', sa.JSON(), nullable=True),
    sa.Column('created_at_utc', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('countries',
    sa.Column('code', sa.String(length=2), nullable=False),
    sa.Column('name_ru', sa.String(length=64), nullable=False),
    sa.Column('name_en', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_table('users',
    sa.Column('telegram_id', sa.BigInteger(), nullable=False),
    sa.Column('first_name', sa.String(length=64), nullable=True),
    sa.Column('username', sa.String(length=32), nullable=True),
    sa.Column('created_at_utc', sa.DateTime(), nullable=False),
    sa.Column('deleted_at_utc', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('telegram_id')
    )
    op.create_table('cities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('country_code', sa.String(length=2), nullable=False),
    sa.Column('name_ru', sa.String(length=128), nullable=False),
    sa.Column('name_en', sa.String(length=128), nullable=False),
    sa.Column('name_local', sa.String(length=128), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('timezone_iana', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['country_code'], ['countries.code'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('friendships',
    sa.Column('user_a_id', sa.BigInteger(), nullable=False),
    sa.Column('user_b_id', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_at_utc', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_a_id'], ['users.telegram_id'], ),
    sa.ForeignKeyConstraint(['user_b_id'], ['users.telegram_id'], ),
    sa.PrimaryKeyConstraint('user_a_id', 'user_b_id')
    )
    op.create_table('visibility_settings',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('level', sa.String(length=16), nullable=False),
    sa.Column('granularity', sa.String(length=16), nullable=False),
    sa.Column('invisible_mode', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.telegram_id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('locations',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('country_code', sa.String(length=2), nullable=False),
    sa.Column('city_id', sa.Integer(), nullable=False),
    sa.Column('updated_at_utc', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['city_id'], ['cities.id'], ),
    sa.ForeignKeyConstraint(['country_code'], ['countries.code'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.telegram_id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('locations')
    op.drop_table('visibility_settings')
    op.drop_table('friendships')
    op.drop_table('cities')
    op.drop_table('users')
    op.drop_table('countries')
    op.drop_table('analytics_events')
    # ### end Alembic commands ###
